export const home = (req, res) => res.render('home')
export const see = (req, res) => res.render('watch')
export const edit = (req, res) => res.send('<h1>Edit Video</h1>')
export const search = (req, res) => res.send('<h1>Search Video</h1>')
export const remove = (req, res) => res.send('<h1>Remove Video</h1>')
export const upload = (req, res) => res.send('<h1>Upload Video</h1>')
